### ISSUE TITLE
Storybook build issues after updating to 4.6.1

### ISSUE THREAD

**Issue by rickydidaravong** [ccpu/storybook-addon-playwright#19]
After updating to 4.6.1, we are not able to perform a Storybook build successfully with these following add-ons:
```
'@storybook/addon-knobs/register',
'storybook-addon-playwright/preset',
'storybook-addon-playwright/register',
```

```
ERR! Module not found: Error: Can't resolve '@storybook/addon-knobs/dist/cjs/shared' in '/Users/***/***/***/node_modules/storybook-addon-playwright/dist/hooks'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-knobs/dist/cjs/shared' in '/Users/***/***/***/node_modules/storybook-addon-playwright/dist/hooks'


Field 'browser' doesn't contain a valid alias configuration
```

Just curious if anyone else is having issues. However if the following is updated to this below, then playwright isn't functional with Storybook.
```
'@storybook/addon-knobs',
'storybook-addon-playwright',
```

**Comment by ccpu** [comment]
what version of storybook your are using? maybe you are using older version of storybook! currently I am using the plugin with storybook `6.2.3` version with no problem. unfortunately I haven't had a chance to test it with latest story book version.

**Comment by rickydidaravong** [comment]
These are the current versions I've updated to recently. However before I was having issues with Storybook `6.2.8`. So I'm guessing I may need to downgrade to `6.2.3`? Just curious could my build issue be related to the `addon-knobs` package now being depreciated? 

"@storybook/addon-actions": "^6.3.4",
"@storybook/addon-controls": "^6.3.4",
"@storybook/addon-essentials": "^6.3.4",
"@storybook/addon-knobs": "6.2.9",
"@storybook/addon-links": "^6.3.4",
"@storybook/react": "^6.3.4",
"@storybook/storybook-deployer": "^2.8.10",

**Comment by ccpu** [comment]
yes, for now, the solution is to down gird to `6.2.3` version, I will try to test it with the latest storybook version when I get a chance, I hope it's not related to `addon-knobs`, because the plug heavily uses this plugin.

**Comment by rickydidaravong** [comment]
Sounds good, thanks for verifying and be on the lookout for that future update!

**Comment by ccpu** [comment]
just updated plugin with latest storybook version, please try again.
