### ISSUE TITLE
Installation fails on macOS 12

### ISSUE THREAD

**Issue by z0n** [ccpu/storybook-addon-playwright#25]
Hi, I tried to install this on my macOS 12 machine and it fails during the Playwright installation: 
```
Error: Failed to download chromium, caused by
Error: ERROR: Playwright does not support chromium on mac12
```

This is caused by the old Playwright version in the dependencies, macOS 12 is supported by >=1.13.0 If I see this correctly. The current version is 1.16.3 (1.17.0 coming very soon).

**Comment by ccpu** [comment]
Hi there, this plugin only works with playwright '1.10' and storybook '6.3', unfortunately i don't have a time to maintain the project, so will archive it soon.

**Comment by z0n** [comment]
Too bad, this actually looks quite useful :(
