### ISSUE TITLE
Error: Configuration has not been set.

### ISSUE THREAD

**Issue by XiaoW9596** [ccpu/storybook-addon-playwright#33]
Hi there, thanks for this amazing addon!

I followed your guide and went through all documentation and issues, but I got `Configuration has not been set.` status code 500 error with api call `/screenshot/get `and `getTheme`. I also tried your example repo, same api error also appeared.

I know that this error message indicates `setConfig()` is empty or not properly read, but I did put required `setConfig()` as documentation, and I couldn't figure out the way to fix this.

This is a screenshot of error when I run your example repo:
<img width="600" alt="Screen Shot 2022-02-17 at 5 59 09 PM" src="https://user-images.githubusercontent.com/83469534/154734682-94d0c00c-da86-4d03-ba90-6b243b9cd46b.png">

This is a screenshot of error when I run my own repo:
![Screen Shot 2022-02-18 at 12 07 54 PM](https://user-images.githubusercontent.com/83469534/154734761-37445273-afff-4456-ad15-7c6748a2c565.png)

Also, even after I delete  `setConfig()` script in main.js, the screenshot/get api still calls for all browsers:
![Screen Shot 2022-02-18 at 12 08 01 PM](https://user-images.githubusercontent.com/83469534/154735015-d5fe40c4-05c8-459b-b8fc-dab32d7fd9fd.png)

I'm not sure if I missed anything as configuration / setup. Thanks in advance for your help!

**Comment by XiaoW9596** [comment]
Hi there, thanks for the quick reply! I installed corresponding package version for playwright, storybook and storybook/addon-knobs and placed `setConfig` inside `main.js`. With different console.log(), I think the error originate from `UnhandledPromiseRejectionWarning: browserType.launch: Browser closed.`

**Comment by ccpu** [comment]
Despite this, I am unable to help you much when it comes to the `playwright` environment. Are you able to launch the playwright browser without this plugin? You can check playwright functionality by running the following code in NodeJS. (try to run this code with all browser Chromium, Firefox, Webkit)

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage()
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('https://playwright.dev/')
  await page.screenshot({ path: 'my_screenshot.png' })
  await browser.close()
})()
```

**Comment by XiaoW9596** [comment]
Hi there, I fixed the error!!! I upgrade the node version to 14.15.0, and then install playwright. Everything works fine right now!

**Comment by XiaoW9596** [comment]
I also runned 
```
npm i -D @playwright/test
# install supported browsers
npx playwright install
```
from https://playwright.dev/docs/1.17/intro

**Comment by ccpu** [comment]
Nice one, now that you have solved the problem, I am closing the issue.
