### ISSUE TITLE
Not able to run storybook after 'storybook-addon-playwright' installation

### ISSUE THREAD

**Issue by ma2kutty** [ccpu/storybook-addon-playwright#46]
I am gettin the following error when i execute 'npm run storybook' after 'storybook-addon-playwright' installation

'Error: VirtualModulePlugin generate with storybook not found! possibly file name changed.'

I debugged for some time but could not get any clue, can somebody help me with this?

Version: "storybook-addon-playwright": "^4.13.11"

**Comment by ccpu** [comment]
Do you have correct version of storybook installed? this plugin only works with storybook@~6.4 and playwright ~1.17.
